# Generated by Django 4.2.1 on 2023-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_done',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
