# Generated by Django 4.2.1 on 2023-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_order_is_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
