# Generated by Django 4.2.1 on 2023-06-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_orderitem_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
    ]
