# Generated by Django 4.2.1 on 2023-06-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_order_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
