# Generated by Django 4.2.1 on 2023-06-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_payment_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
