# Generated by Django 4.2.1 on 2023-06-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_feedback_title_alter_feedback_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Order',
            new_name='order',
        ),
    ]
