# Generated by Django 4.2.1 on 2023-06-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_order_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='Order',
        ),
    ]
