# Generated by Django 4.2.1 on 2023-07-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_order_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
