# Generated by Django 4.2.1 on 2023-06-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_waiter',
            field=models.BooleanField(default=False, verbose_name='Is waiter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
