# Generated by Django 4.2.1 on 2023-07-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, error_messages={'max_length': 'Max length exceeded 10', 'unique': 'Mobile number already exists'}, max_length=10, null=True, unique=True),
        ),
    ]
