# Generated by Django 4.2.1 on 2023-07-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(blank=True, error_messages={'unique': 'Mobile number already exists'}, null=True, unique=True),
        ),
    ]
