# Generated by Django 4.2.1 on 2023-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
