# Generated by Django 4.2.1 on 2023-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='offer_price',
            field=models.FloatField(),
        ),
    ]
