# Generated by Django 4.2.1 on 2023-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
